export * from './collage/Collage'
export * from './footer/Footer'
export * from './header/Header'
export * from './left-product/LeftProduct'
export * from './news-letter/NewsLetter'
export * from './right-product/RightProduct'